#!/bin/bash
# WSL 'git' wrapper, save as /usr/local/bin/git and chmod a+x

REALPATH=`readlink -f ${PWD}`
ARG1=$1

if [ "${REALPATH:0:3}" == "/c/" ]; then
  if [ "$ARG1" == "log" ]; then
    /c/Users/GLamb/bin/cmd.exe /c git.exe "$@" | more
  else
    /c/Users/GLamb/bin/cmd.exe /c git.exe "$@"
  fi
else
  /usr/bin/git "$@"
fi

